name: 'eks-kubectl'
author: Vyacheslav G.
description: kubectl tool with AWS SDK for EKS easy access (forked from Ian Belcher's repo)
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/gvych/eks-kubectl-action'
inputs:
  aws_access_key_id:
    description: Your AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: Your AWS_SECRET_ACCESS_KEY
    required: true
  aws_region:
    description: The region of the cluster
    required: true
  cluster_name:
    description: The name of the cluster you're using
    required: true
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
  
